# Generated by Django 6.0.3 on 2026-03-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update_note',
            field=models.CharField(blank=True, help_text="Write the new tech update here (e.g., 'Upgraded to 800W motor')", max_length=255, null=True),
        ),
    ]
