# Generated by Django 6.0.3 on 2026-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_update_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Headline of the update (e.g., 'New 800W Motor Added')", max_length=200)),
                ('description', models.TextField(help_text='Full details of the update')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recent_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recent Update',
                'verbose_name_plural': 'Recent Updates',
            },
        ),
    ]
